### ISSUE TITLE
Getting erros trying to extract zip folder

### ISSUE THREAD

**Issue by mekatech101** [udacity/nd063-c2-design-for-availability-resilience-reliability-replacement-project-starter-template#1]
I keep getting errors trying to extract folder and when I skip the error, the files are extracted but when I'm trying to create the stack and upload the vpc.yaml file, the stack creation always rolls back and deletes all the resources being created. Why is that?

**Comment by SudKul** [comment]
Please refer to the detailed error message in the CFN console. 
Also, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can benefit from the discussion.
