### ISSUE TITLE
if you execute 'create stack'  using for vpc.yaml as template, you'll get Template format error

### ISSUE THREAD

**Issue by yoda3035** [udacity/nd063-c2-design-for-availability-resilience-reliability-replacement-project-starter-template#2]
for /cloudformation/vpc.yaml if you use it in AWS console there will be 
'Template format error: YAML not well-formed. (line 121, column 65)'
can you please take a look?
thank you

**Comment by SudKul** [comment]
Hey @yoda3035 
YAML is highly space sensitive. 
I checked today, and it seems to be fine. However, one can always check the indentations using third-party tools, such as http://www.yamllint.com/. 

If you find any incorrect syntax, feel free to submit a PR.
